name: Continuous Integration
on: [push]
jobs:
  test:
    strategy:
      matrix:
        image:
          - ubuntu-latest
          - windows-latest
          - macos-latest # ARM
          - macos-13 # Intel

    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  miri:
    strategy:
      matrix:
        image:
          - ubuntu-latest
          - windows-latest
          - macos-latest # ARM
          - macos-13 # Intel

    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - run: cargo +nightly miri test
